services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server","--appendonly","yes","--requirepass","Passw0rd!"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      ##- "5672:5672"   # AMQP
      - "15673:15672" # management UI http://localhost:15672 (guest/guest)
  postgres:
    image: postgres:16
    container_name: pg-users
    restart: unless-stopped
    environment:
      POSTGRES_USER: useradmin
      POSTGRES_PASSWORD: "Passw0rd!"
      POSTGRES_DB: moviedb
    ports:
      # if 5432 is busy locally, change to "5433:5432"
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data   # <- old volume
      # auto-run any .sql or .sh files on first startup
      - ./init:/docker-entrypoint-initdb.d

  # Optional admin UI
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: "Passw0rd!"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin    # <-- persist pgAdmin config
  bookingservice:
   build:
    context: .
    dockerfile: BookingService/Dockerfile
   environment:
    ASPNETCORE_URLS: http://0.0.0.0:8080
    Rabbit__Host: rabbitmq
    Rabbit__Username: guest
    Rabbit__Password: guest
   depends_on: [rabbitmq, postgres, redis]
   ports:
    - "5001:8080"
  notificationservice:
   build:
    context: .
    dockerfile: NotificationService/Dockerfile
   environment:
    ASPNETCORE_URLS: http://0.0.0.0:8080
    Rabbit__Host: rabbitmq
    Rabbit__Username: guest
    Rabbit__Password: guest
   depends_on: [rabbitmq]
   ports:
    - "5002:8080"

volumes:
  pgdata:
  pgadmin-data:  
  redisdata:    